#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## BSPWM config file for Archcraft

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Bspwm colors
BSPWM_FBC='#81A1C1'
BSPWM_NBC='#2E3440'
BSPWM_ABC='#B48EAD'
BSPWM_PFC='#A3BE8C'

## Bspwm appearance
BSPWM_BORDER='1'
BSPWM_GAP='10'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#

## Manage Monitors and Workspaces
##
## Default Setup (Set 8 workspaces on each monitor)
default_workspaces() {
	for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
		bspc monitor "$monitor" -d '' '' '' '' '' '' '' '' '' ''
	done
}

## Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)
two_monitors_workspaces() {
	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	MONITOR_1="DP-2"
	MONITOR_2="DP-4"
	if [[ $(xrandr -q | grep "${MONITOR_2} connected") ]]; then
		bspc monitor "$MONITOR_2" -d '' '' '' '' ''
		bspc monitor "$MONITOR_1" -d '' '' '' '' '' 
		bspc wm -O "$MONITOR_1" "$MONITOR_2" 
	else
		bspc monitor "$MONITOR_1" -d '' '' '' '' '' '' '' '' '' ''
	fi
}

## Three Monitors Setup (Laptop and two external monitor, 3-2-3 workspaces)
three_monitors_workspaces() {
	# again, change these values accordingly
	MONITOR_1="DP-2"
	MONITOR_2="DP-4"
	MONITOR_3="HDMI-A-1"
	bspc monitor "$MONITOR_1" -d '' '' 
	bspc monitor "$MONITOR_2" -d '' '' '' 
	bspc monitor "$MONITOR_3" -d '' '' '' '' ''
	bspc wm -O "$MONITOR_2" "$MONITOR_1" "$MONITOR_3"
}

## Uncomment only one function according to your needs
#default_workspaces
two_monitors_workspaces
#three_monitors_workspaces

## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

## remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
bspc rule -a Kitty desktop='^1' follow=on focus=on
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

## 2 > code (always open editors on workspace-2)
declare -a code=(Geany code-oss Code code Xed xed)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

## 3 > office and docs (always open office/doc apps on workspace-3)
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

## 4 > grafx (always open grafx apps on workspace-4)
declare -a grafx=(Inkscape Gimp)
for i in ${grafx[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

## 5 > web (always open tools on workspace-5)
bspc rule -a GParted desktop='^5' follow=on focus=on
bspc rule -a Navigator desktop='^5' follow=on focus=on
bspc rule -a KeePassXC desktop='^5' follow=on focus=on
bspc rule -a Xreader desktop='^5' state=tiled follow=on focus=on
bspc rule -a Meld desktop='^5' follow=on focus=on

## 6 > web (always open web browser on workspace-6)
bspc rule -a Google-chrome desktop='^6' follow=on focus=on
bspc rule -a chromium desktop='^6' follow=on focus=on

## 7 > communication (always open communication apps on workspace-7)
declare -a comm=(Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^7' follow=on focus=on; done

## 8 > files (always open file manager on workspace-8)
bspc rule -a Thunar desktop=^8 follow=on focus=on

## 9 > media (always open media apps on workspace-9)
declare -a media=(Audacity Music MPlayer Lxmusic Spotify)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^9' follow=on focus=on; done

## 10 > system (always open system apps on workspace-10)
bspc rule -a 'VirtualBox Manager' desktop='^10' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^10' state=floating follow=on focus=on; done

## Always Floating Apps
declare -a floating=(alacritty-float kitty-float Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor calamares Calamares)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a stalonetray state=floating manage=off


## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
#xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash ~/.fehbg
#nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
# Network Applet
nm-applet --indicator &

# Start mpd
exec mpd &

# Start bspwm scripts
bspbar
bspcomp
bspdunst
# script forces all new windows on desktop 8 to be floating
#bspfloat &

